### ISSUE TITLE
Publish rpm package

### ISSUE THREAD

**Issue by KillDozerX2** [cemalgnlts/Mailjs#1]
It might be a good idea to release a package to npm or GitHub packages

**Comment by cemalgnlts** [comment]
Yes, I will be releasing an npm package soon.

**Comment by KillDozerX2** [comment]
Do you want a pr? I can setup semantic releases too if you want, we could use this in our app development life cycle. It's upto you

**Comment by cemalgnlts** [comment]
Only the following should go to NPM:
* NodeJS/Mailjs.js
* README.md (not NodeJS/README.md)

I'm not sure how to do this, maybe we can create a `package.json` and add what needs to go into it.

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files

**Comment by cemalgnlts** [comment]
Added to NPM thanks.
