### ISSUE TITLE
Make eventsource.min.js really optional

### ISSUE THREAD

**Issue by anonghuser** [cemalgnlts/Mailjs#10]
The README says this about `eventsource.min.js`:
```
<!-- you can exlude this if not listening to events (may cause runtime error) -->
```
But the way it is bundled, it always throws an `EventSourcePolyfill is not defined` error even if you don't use events.

You should change the `output.globals.eventsource` rollup config value from `EventSourcePolyfill` to `globalThis.EventSourcePolyfill` so it just resolves to undefined when missing instead of throwing an error. Then indeed the error will only happen when you try to use events and not every time.

**Comment by cemalgnlts** [comment]
Hi,

Thanks for the suggestion. I will try to fix the problem.
