### ISSUE TITLE
Latest version does not work for browser

### ISSUE THREAD

**Issue by brian-b8fd** [cemalgnlts/Mailjs#11]
The quickstart code from the readme gives errors when ran in a browser.
The code:
```
<script src="https://cdn.jsdelivr.net/gh/cemalgnlts/Mailjs@latest/mailjs.min.js"></script>

<!-- you can exlude this if not listening to events (may cause runtime error) -->
<script src="https://cdn.jsdelivr.net/gh/cemalgnlts/Mailjs@latest/eventsource.min.js"></script>

<script>
	const mailjs = new Mailjs();
</script>
```

The errors: `Uncaught ReferenceError: EventSourcePolyfill is not defined` on line 1 of mailjs.min.js and `Uncaught TypeError: Mailjs is not a constructor` on line 6 of the example code.

The example in the examples folder works fine. This is because that example uses version 2.0. Changing "latest" in the quickstart code to 2.0 makes it work. But then I'm unfortunately missing out from the new features in 2.2.

**Comment by cemalgnlts** [comment]
Thanks,

I'll check the error.
