### ISSUE TITLE
ReferenceError: fetch is not defined in Nodejs

### ISSUE THREAD

**Issue by vietnamghost95** [cemalgnlts/Mailjs#13]
const res = await fetch(this.baseUrl + path, options);
                    ^

ReferenceError: fetch is not defined

please add node-fetch

**Comment by cemalgnlts** [comment]
Hi,

I thought nobody would use `node-fetch` after `node v16.20.2`.

Using `nvm` maybe it will be easier to upgrade the node version on your device.

**Comment by cemalgnlts** [comment]
I am closing this issue for now and you can open it again if you have any questions.
