### ISSUE TITLE
Delete Multiple emails

### ISSUE THREAD

**Issue by Emmathem** [cemalgnlts/Mailjs#2]
If I have to delete many emails, I had to delete one after the other. 

Can batch deletion be implemented? Just an enhancement to the system. 

Nice job.

**Comment by cemalgnlts** [comment]
Hi,

There is no support for this in mail.tm, but if you keep the id's somewhere you can delete them using a loop.

I haven't tested it, but this should work for you.

```js
const ids = [1, 2, 3, 4];

const results = ids.map(async (id) => {
    const res = await mailjs.deleteMessage(id);
    return res;
});

Promise.all(results)
  .then(console.log);
```

Or:
```js
// All mails.
const mails = [{...}, {...}];

const results = mails.map(async (mail) => {
    // console.log(mail.subject);
    const res = await mailjs.deleteMessage(mail.id);
    return res;
});

Promise.all(results)
  .then(console.log);
```

**Comment by Emmathem** [comment]
Thank you @cemalgnlts for that. I found a way around it earlier but I was getting error 429 (too many requests) but working fine with the code below

```

// using reactjs with useState()
const StartDeleteMails = async () => {
    setloading(true);
    for (let i = 0; i < tm_mails?.length; i++) {
      const tm_id = tm_mails[i].id;
      if (tm_id) {
        const res = await DeleteSingleMail(tm_id);
        setloading(false);
        if (res.success) {
          setloading(false);
        } // break;
      }
      await GetAllMails();
    }
  };

```

**Comment by cemalgnlts** [comment]
@Emmathem https://docs.mail.tm/#access-to-the-api
> The general quota limit is 8 queries per second (QPS) per IP address.
