### ISSUE TITLE
Setting a token

### ISSUE THREAD

**Issue by mr-akashdesai** [cemalgnlts/Mailjs#4]
Hi, I was wondering if would it be possible to create a method to set the token? Currently, the token has a private type so you can't override it. I want to do this because then I can store the token in localStorage and reauthenticate with the client, keeping the user signed in and not having to login every time. (p.s. not sure how long the JWT token actually lasts for, so it may not be ideal.) 

Let me know what you think and if there's another way to keep the user logged in.

**Comment by cemalgnlts** [comment]
Hi,

There is currently no feature for this. But you can directly forward the token to the created instance.
```js
const mailjs = new Mailjs();
mailjs.token = "MY_TOKEN";
```
This method will not give you the user ID and address so to solve this problem you will need a function to give the id and address information after issuing the token.

```js
async function loginWithToken(token) {
  const mailjs = new Mailjs();
  mailjs.token = token;

  const res = await mailjs.me();

  // Throw the error message if the request failed.
  if(!res.status) throw new Error(res.message);

  mailjs.id = res.data.id;
  mailjs.address = res.data.address;

  return mailjs;
}

function loginSuccess(mailjs) {
  // mailjs maintains an authorized instance.
}

loginWithToken("MY_TOKEN")
  .then(loginSuccess)
  .catch(console.error)
```

I hope this will work for you.

**Comment by mr-akashdesai** [comment]
Hi,

Yeah so this was my initial plan to set the token however as I mentioned, the token has a private type assigned to it, so you can't overwrite it. Not sure if this is a bug with the TypeScript typings, but this is what I get when I try to override the token. This is why I wasn't sure if it was possible or not. 

<img width="615" alt="image" src="https://user-images.githubusercontent.com/43957034/182041670-77272d3d-d87e-47ff-8aaf-69ead2710049.png">
<img width="623" alt="image" src="https://user-images.githubusercontent.com/43957034/182041709-d1e1603f-2643-48d8-8921-18a23057bb3c.png">

**Comment by cemalgnlts** [comment]
Yes, you are right.
I added TypeScript to the project later, I don't remember why I used it with private.  Maybe I can add a new function.

But overriding TypeScript for that line might be a workaround.

```
// @ts-ignore:next-line
```

**Comment by mr-akashdesai** [comment]
Sure, no worries, I was just wondering. Thanks for the help. 🙂

**Comment by cemalgnlts** [comment]
If anyone is wondering, there is a method for this now. 27d8b95b737c81210feae24931309562f1d1318b
