### ISSUE TITLE
createOneAccount() types are not correct

### ISSUE THREAD

**Issue by baciucristian** [cemalgnlts/Mailjs#7]
I'm new to TypeScript, so I'm not sure if this is a bug.
When I try to access the returned object of `createOneAccount()`, it doesn't recognize the `data.username`, just the `data`.
```js
async createEmail() {
  const mailAccount = await this.mailJS.createOneAccount();
  return mailAccount;
}
```
![image](https://user-images.githubusercontent.com/49842769/228030068-5df3b2de-0696-483e-a952-972956e30bb0.png)
![image](https://user-images.githubusercontent.com/49842769/228030090-dfc6e7b5-1b18-43f7-a436-8aed132ecb39.png)

**Comment by cemalgnlts** [comment]
Hi,

Yes, there seems to be a problem with the type declaration.
