### ISSUE TITLE
CDNs do not include mailjs.min.js built for use in browser

### ISSUE THREAD

**Issue by anonghuser** [cemalgnlts/Mailjs#9]
Check out [https://unpkg.com/@cemalgnlts/mailjs/](https://unpkg.com/@cemalgnlts/mailjs/) or [https://cdn.jsdelivr.net/npm/@cemalgnlts/mailjs/](https://cdn.jsdelivr.net/npm/@cemalgnlts/mailjs/)

They are pretty barebones compared to the git repo, because of the `files` field in the `package.json`. Most notably, they lack the `mailjs.min.js` needed for use in browsers.

In the README example for use in browser, you give a jsdeliver link that uses special syntax for the github repo instead of the npm package, but people searching for the module on the cdn normally may not think to do so.

Perhaps you should add `mailjs.min.js` to `files` and/or `browser` field and/or move it to `dist` folder to make the module more easily usable in browsers without people having to look up the example with using jsdeliver special syntax for github?

**Comment by cemalgnlts** [comment]
Hi,
Yes, you are right.

I will add mailjs.min.js to the browser field and see the result.
